#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

declare papertrail_endpoint=`config-get endpoint`


#Should probably look for the exact string
if ! grep -qe ".papertrail" /etc/rsyslog.conf; then 
    echo "# PapertrailApp Log Aggregator" >> /etc/rsyslog.conf; 
    echo "*.*     @$papertrail_endpoint" >> /etc/rsyslog.conf; 
    juju-log "Installed Papertrail syslog support"
fi

service rsyslog restart
