#!/bin/bash

set -ex

declare syslog_endpoint=`config-get syslog_endpoint`
declare rsyslog_string="*.*    @$endpoint"
declare applicationlogs=`config-get applicationlogs`
declare  monitorall=`config-get monitorall`

# install rsyslog monitoring
if [ "$syslog_endpoint" -eq null ]; then
 	juju-log "Papertrail not configured"
 	return 0
fi

# Check if we should re-run the installer due to config changes
if [ $monitorall != "false" ] || [ $applicationlogs != null ] then
	hooks/install
fi

if [ -a "/etc/rsyslog.d/25-papertrail.conf" ]; then 
	rm /etc/rsyslog.d/25-papertrail.conf
	juju-log "Removed stale papertrail configuration"
fi


echo "$rsyslog_string" >> /etc/rsyslog.d/25-papertrail.conf; 
juju-log "Updated Papertrail rsyslog support"



