#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

# re-run the installation script

declare syslog_endpoint=`config-get syslog_endpoint`
declare rsyslog_string="*.*    @$endpoint"


# install rsyslog monitoring
	
if [ "$syslog_endpoint" -eq "" ]; then
 	juju-log "Papertrail not configured"
 	return 0
fi

if [ -a "/etc/rsyslog.d/25-papertrail.conf" ]; then 
    rm /etc/rsyslog.d/25-papertrail.conf
    juju-log "Removed stale papertrail configuration"
fi

echo "$rsyslog_string" >> /etc/rsyslog.d/25-papertrail.conf; 
juju-log "Updated Papertrail rsyslog support"


