#!/bin/bash


# Install Dependencies for Application Logging
# Install ruby 1.9.3 for latest -stable tree. 
# TODO: Ruby changes fairly often, make this configurable 
apt-get install -y ruby1.9.3 build-essential 

# Install papertrails application logging support
gem install remote_syslog --no-ri --no-rdoc

#its not unlikely that this will change in the future
declare endpoint=`logs.papertrailapp.com`
declare port=`config-get port`
declare rsyslog_string="*.*    @$endpoint:$port"


#Determine Syslog Agent - Papertrail lists support for
# Rsyslog, syslog-ng, syslog.conf - see: https://papertrailapp.com/systems/setup

#todo: support syslog-ng with cheetah template
#todo: support GNU Syslog with remote_syslog gem


# if [ -a /etc/rsyslog.conf ] then
# 	declare papertrail_agent="rsyslog"
# 	juju-log "Papertrail - detected rsyslog"
# fi



# install rsyslog monitoring
	
if [ $port -eq 0 ]; then
	juju-log "Papertrail not configured"
	return 1
fi

if ! grep -qe "$endpoint" /etc/rsyslog.conf; then 
    echo "$papertrail_string" >> /etc/rsyslog.conf; 
    juju-log "Installed Papertrail rsyslog support"
else
	sed "/$papertrail_string/d" -i /etc/rsyslog.conf
	echo "$papertrail_string" >> /etc/rsyslog.conf;
	juju-log "Installed Papertrail rsyslog support"
fi

