#!/bin/bash

set -ex 

declare application_log=`config-get applicationlogs`
declare monitorall=`config-get monitorall`

#TODO: Provide installation hooks for nxlog-ce for
# a non-ruby alternative

if [ "$application_log" != "" ] || [ "$monitorall" != "false" ]; then
	# Install Dependencies for Application Logging
	# Install ruby 1.9.3 for latest -stable tree. 
	# TODO: Ruby changes fairly often, make this configurable 
	apt-get install -y ruby1.9.3 build-essential 

	# Install papertrails application logging support
	gem install remote_syslog --no-ri --no-rdoc
fi

