#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

#apt-get install -y papertrail
declare papertrail_endpoint=`config-get endpoint`
declare papertrail_string="*.*    @$papertrail_endpoint"

if ! grep -qe "$papertrail_string" /etc/rsyslog.conf; then 
    echo "$papertrail_string" >> /etc/rsyslog.conf; 
    juju-log "Installed Papertrail syslog support"
fi

service rsyslog restart
