#!/bin/sh
# This hook runs when the full relation is removed (not just a single member)

if [ -a "/etc/rsyslog.d/25-papertrail.conf" ]; then
	rm /etc/rsyslog.d/25-papertrail.conf
fi

if [ -a "/tmp/papertrail_monitor.pid"  ]; then
	kill -9 `cat /tmp/papertrail_monitor.pid`
fi

if [ -a "/tmp/papertrail_application.pid"  ]; then
	kill -9 `cat /tmp/papertrail_application.pid`
fi


service rsyslog restart