#!/bin/bash

if [ -a "/tmp/papertrail_monitor.pid"  ]; then
	kill -9 `cat /tmp/papertrail_monitor.pid`
fi

if [ -a "/tmp/papertrail_application.pid"  ]; then
	kill -9 `cat /tmp/papertrail_application.pid`
fi

rm /etc/rsyslog.d/25-papertrail.conf

service rsyslog restart