#!/bin/bash

service rsyslog restart

if [ -a "/tmp/papertrail_monitor.pid"  ]; then
	kill -9 `cat /tmp/papertrail_monitor.pid`
fi

if [ -a "/tmp/papertrail_application.pid"  ]; then
	kill -9 `cat /tmp/papertrail_application.pid`
fi
